Alpine support
ema/pets pull request #6
Opened 2022-11-03 02:53 UTC by melezhik

This is just a draft. For some reasons some of tests fail on SparrowCI - https://ci.sparrowhub.io/report/1488

2022-11-03 03:07 UTC, melezhik commented
```
02:54:29 :: 2022/11/03 02:54:29 [INFO] coreutils not installed
02:54:29 :: 2022/11/03 02:54:29 [ERROR] running /sbin/apk info -qe freedoom: 'exit status 1'
02:54:29 :: 2022/11/03 02:54:29 [INFO] freedoom not installed
02:54:29 :: --- FAIL: TestPkgsToInstall (0.07s)
```

I guess this is because coreutils are not preinstalled on vanilla Alpine Linux

2022-11-03 03:10 UTC, melezhik commented
it boils down to this assumption (not met on Alpine) -  https://github.com/ema/pets/blob/master/planner_test.go#L15-L17

```go
  // Test with one package already installed
  pf, err := NewPetsFile("/dev/null", "coreutils", "/etc/passwd", "root", "root", "0640", "", "")
  assertNoError(t, err)
```

2022-11-03 03:16 UTC, melezhik commented
```
util.go:79: /bin/chmod 0644 /dev/null != /usr/bin/chmod 0644 /dev/null
```

This is because assumption for location of `chmod` for alpine  is wrong - https://github.com/ema/pets/blob/e3d78d14564745f4f69c58e5642a1fe353557e75/planner_test.go#L112

```go
pa := Chmod(pf)
  if pa != nil {
    t.Errorf("Expecting nil, got %v instead", pa)
  }

  pf.AddMode("0644")

  pa = Chmod(pf)

  assertEquals(t, pa.Cause.String(), "CHMOD")
  assertEquals(t, pa.Command.String(), "/usr/bin/chmod 0644 /dev/null")
```

it's indeed at `/bin/chmod`

2022-11-14 18:28 UTC, ema requested changes
Two comments, LGTM otherwise! Thanks.

2022-11-14 18:28 UTC, ema commented on package.go
> +  return nil
Indentation looks off here, please use `go fmt`.

2022-11-14 18:28 UTC, ema commented on package.go
> +			log.Printf("[ERROR] running %s: '%s'", installed, err)
Missing `\n`.

2022-11-14 18:38 UTC, melezhik commented
please see now ...

2022-11-15 09:56 UTC, ema approved these changes
Nice, thank you!

2022-11-15 09:56 UTC, merged